### ISSUE TITLE
found issue

### ISSUE THREAD

**Issue by Al3601** [Jackybeat/ArkDiscordBot#1]
Hi, 
fisrt of all thank you for your work , i just found an issue, all is working except the " ARK_CHAT_CHANNEL = 'chat_ark'" , i got nothing in that channel , only logs on the log_ark channel.

do you have the same problem ?

**Comment by Jackybeat** [comment]
Hi,
This feature is not yet implemented.

You can try to implement it by reworking ArkDiscordBot/ArkDiscordBot/tasks/ark_chat.py
You can take exemple at ArkDiscordBot/ArkDiscordBot/tasks/ark_logs.py
